### ISSUE TITLE
how could I get the primer fasta files?

### ISSUE THREAD

**Issue by Gerosyclouds** [aakechin/cutPrimers#4] opened 2018-04-13 06:26 UTC
Hi，
I have a primer bed file:
Chr     Amplicon_Start  Insert_Start    Insert_Stop     Amplicon_Stop
chr17   41275996        41276024        41276122        41276149
chr17   41267705        41267733        41267856        41267884
How could I get the primer fasta files?

When I run the shell from the readme file,
'''
python3 cutPrimers.py -r1 example/1_S1_L001_R1_001.fastq.gz -r2 example/1_S1_L001_R2_001.fastq.gz -pr15 example/primers_R1_5.fa -pr25 example/primers_R2_5.fa -pr13 example/primers_R1_3.fa -pr23 example/primers_R2_3.fa -tr1 example/1_r1_trimmed.fastq.gz -tr2 example/1_r2_trimmed.fastq.gz -utr1 example/1_r1_untrimmed.fastq.gz -utr2 example/1_r2_untrimmed.fastq.gz -t 2
'''
As a result I get four files with the following sizes: 4.2 Mb, 2.3 Mb, 3.6 Mb and 2.3 Mb for files with trimmed R1 reads, untrimmed R1 reads, trimmed R2 reads and untrimmed R2 reads, respectively. 
But I find some the primer sequences are still in the untrimmed reads files,why?
less primers_R1_5.fa|head
> R1
**AGAGTGGGTGTTGGACAGTGT**

less 1_S1_L001_R1_001.untrim.fastq.gz|grep **AGAGTGGGTGTTGGACAGTGT**
GATTAGAGCCTAGTCCAGGAGAATGAATTGACACTAATCTCTGCTTGTGTTCTCTGTCTCCAGCAATTGGGCAGATGTGTGAGGCACCTGTGGTGACCCGAGAGTGGGTGTTGGACAGTGTAGCACTCTACCAGTGCCAGGAAATCACCGA
**AGAGTGGGTGTTGGACAGTGT**AGCACTCTACCAGTGCCAGGAGCTGGACACCTACCTGATACCCCAGATCCCCCACAGCCACTACTGACTGCAGCCAGCCACAGGTACAGAGCCACAGGACCCCAAGAATGAGCTTACAAAGTATCACCGA
**AGAGTGGGTGTTGGACAGTGT**AGCACTCTACCAGTGCCAGGAGCTGGACACCTACCTGATACCCCAGATCCCCCACAGCCACTACTGACTGCAGCCAGCCACAGGTACAGAGCCACAGGACCCCAAGAATGAGCTTACAAAGGATCACCGA
GATTAGAGCCTAGTCCGGGAGAATGAATTGACACTAATCTCTGCTTGTGTTCTCTGTCTCCAGCAATTGGGCAGATGTGTGAGGCACCTGTGGTGACCCGAGAGTGGGTGTTGGACAGTGTAGCACTCTACCAGTGCCAGGAAATCACCG
GATTAGAGCCTAGTCCAGGAGAATGAATTGACACTAATCTCTGCTTGTGTTCTCTGTCTCCAGCAATTGGGCAGATGTGTGAGGCACCTGTGGTGACCCGAGAGTGGGTGTTGGACAGTGTAGCACTCTACCAGTGCCAGGAAATCACCGA
**AGAGTGGGTGTTGGACAGTGT**AGCACTCTACCAGTGCCAGGAGCTGGACACCTACCTGATACCCCAGATCCCCCACAGCCACTACTGACTGCAGCCAGCCACAGGTACAGAGCCACAGGACCCCAAGAATGAATCACCGACTGCCCATAGG
**AGAGTGGGTGTTGGACAGTGT**AGCACTCTACCAGTGCCAGGAGCTGGACACCTACCTGATACCCCAGATCCCCCACAGCCACTACTGACTGCAGCCAGCCACAGGTACAGAGCCACAGGACCCCAAGAATGAGCTTACAAATATCACCGA
AGAGTGGGTGTTGGACAGTGTGTGGCTGTGTGGGTCAGTGTATGGCTGTGTGGGTTGGTGAGTGGTTGTGTGGGTTGCTGTGTGTGCGTGTGGGGTGCCTGTTTTGGGGAAAAATAGCTTTTCACATCTGCAATCACCGACTGCCCATAGG
GATTAGAGCCTAGTCCAGGAGAATGAATTGACACTAATCTCTGCTTGTGTTCTCCGTCTCCAGCAATTGGGCAGATGTGTGAGGCACCTGTGGTGACCCGAGAGTGGGTGTTGGACAGTGTAGCACTCTACCAGTGCCAGGACATCACCGA

And I use cutPrimers to deal amplicon fastq, eighty percent reads trimmed, there are still twenty percent reads untrimmed with the primer sequence. How could I solve this problem?

Any help is appreciated.
Best Regards,
Amy

**Comment by aakechin** [comment] 2018-04-13 11:48
@Gerosyclouds, thank for your comment! If you have coordinates of your amplicons, you should extract sequences chr17:41275996-41276023 (e.g. it will be F1), chr17:41276123-41276149 but reverse-complement (e.g. it will be R1). Or if your primers are located on the opposite strands (F1 on the minus strand and R1 on the plus), than you should reverse-complement only F1. In the same way, extract sequences for the second amplicon: chr17:41267705-41267732 (F2) and chr17:41267857-41267884 (R2). If you use hg19 version of human genome, you can extract necessary sequences here: https://www.ncbi.nlm.nih.gov/nuccore/NC_000017.10. If the hg38, then here: https://www.ncbi.nlm.nih.gov/nuccore/NC_000017.11.

After that, you need to create fasta-files with sequences of primers that will be in the reads. If the length of your amplicons is equal to the length of the NGS machine read, than both primer sequences will be on the left and right ends of your reads. If the length of your amplicon is much more than the length of the NGS machine read, primer sequences will be only on their left  ends. If the length of your amplicon is much less than the length of the NGS machine read, primer sequences will be on their left  ends and in the middle of your NGS reads, and your reads will also contain adapter sequences. In the last case, I'd recommend you, first, to trim adapter sequences from NGS reads. In the most of cases, primer sequences will be located in NGS reads in the following manner:
R-primer-----------------------------------------------F-primer (reverse-complemented) - 1st reads of pairs
F-primer-----------------------------------------------R-primer (reverse-complemented) - 2nd reads of pairs
So your files should look like the files that I attached (there are your primer sequences, if you use hg19 version of human reference genome).
[primer_sequences_R2_end3.txt](https://github.com/aakechin/cutPrimers/files/1907148/primer_sequences_R2_end3.txt)
[primer_sequences_R2_end5.txt](https://github.com/aakechin/cutPrimers/files/1907149/primer_sequences_R2_end5.txt)
[primer_sequences_R1_end3.txt](https://github.com/aakechin/cutPrimers/files/1907150/primer_sequences_R1_end3.txt)
[primer_sequences_R1_end5.txt](https://github.com/aakechin/cutPrimers/files/1907151/primer_sequences_R1_end5.txt)

About example files. This can be explained by the presence of unspecific amplicons that have different combinations of primer sequences. cutPrimers searches only reads that have corresponding to each other primers, that is, if you defined primer sequences fot both ends, it will searches primer sequences on both ends. If some read contains primer sequences from different amplicons, it will left it untrimmed. But if you do not want to do it, you can use argument "-primer3".

I hope this will help. Do not hesitate to ask me again. And, please, let me know about the successful or unsuccessful use of the program.

Best regards,
Andrey

**Comment by Gerosyclouds** [comment] 2018-04-16 03:46
Thank you, Andrey.
I don't understand if my primers are located on the opposite strands ,how should I  extract primer sequences?
 "Or if your primers are located on the opposite strands (F1 on the minus strand and R1 on the plus), than you should reverse-complement only F1."
Could you help me convert the region to primer sequence fasta file?
Chr     Amplicon_Start  Insert_Start       Insert_Stop      Amplicon_Stop
chr13   32890543        32890571        32890688        32890716
chr13   32893173        32893199        32893345        32893372


Best regards,
Amy

**Comment by aakechin** [comment] 2018-04-16 04:23
Amy, I meant two cases:
Forward primer is on the plus strand, and reverse is on the minus strand
PRIMER1----------------------------------------------------------
----------------------------------------------------------PRIMER2
But you could locate your primers in the following manner, too (this is very rare):
----------------------------------------------------------PRIMER2
PRIMER1----------------------------------------------------------

To open reference sequence of some human chromosome on the ncbi, you can use https://www.ncbi.nlm.nih.gov/genome/?term=human. But there are reference sequences for hg38 assembly of human genome. You can click on the chromosome assembly of your interest (e.g. NC_000013.11 - 13 is a chromosome number and 11 is its version of assembly), and https://www.ncbi.nlm.nih.gov/nuccore/NC_000013.11 will be opened. To open hg19 version of genome assembly, change last two numbers in the browser link, so it will look like https://www.ncbi.nlm.nih.gov/nuccore/NC_000013.10.
There is parameter "Change region shown" in the upper right corner of the site page. Click on the triangle to the right of this inscription. And write coordinates of your primer. For example, 32890543 instead of "begin" and 32890570 (do not forget to substract 1 because it is a start of insert but you need end of your primer) instead of "end". And press "Update view". In the bottom of the page you will get sequence of your primer. Copy it to the text editor and remove all spaces. In a similar way, you can get a sequence for reverse primer, but you will also need to click on the triangle to the right of "Customize view" and check "Customize" and "Show reverse complement". Again, in the bottom of the page you will get sequence of your reverse primer.

When you get sequenes for all your primers, you will need to create files that will contain primer sequences in the right orientation (see my previous comment).

If I wrote something unclearly, ask me again. Did you manage to remove primer sequences that you asked in your previous question?

**Comment by Gerosyclouds** [comment] 2018-04-19 02:48
Thank you, Andrey.
I use cutPrimers to deal amplicon fastq, eighty percent reads trimmed, there are still twenty percent reads untrimmed with the primer sequence. **Maybe the untrimmed reads are non-specific amplification.** The untrimmed reads are discarded. 
python cutPrimers.py -r1 $fqc1.cutadapt.fq.gz -r2 $fqc2.cutadapt.fq.gz -pr15 $PR15 -pr25 $PR25 -pr13 $PR13 -pr23 $PR23 -tr1 $fqc1.trim.fq.gz -tr2 $fqc2.trim.fq.gz -utr1 $fqc1.untrim.fq.gz -utr2 $fqc2.untrim.fq.gz --error-number 2 -primer3

1.    I set --error-number 2, the following reads are trimmed longer than the primer length. 
>chr13:32900589-32900616
TGATCAGGGCATTTCTATAAAAAATAAA
**[TGATCAGGGCATTTCTATAAAAAATAAAC]**TATTTTCTTTCCTCCCAGGGTCGTCAGGCACCAAAACATATTTCTGAAAGTCTAGGAGCTGAGGTGGATCCTGATATGTCTTGGTCAAGTTCTTTAGCTACACCACCCACCCTTAGTTCTA
**[TGATCAGGGCATTTCTATAAAAAATAAAC]**TATTTTCTTTCCTCCCAGGGTCGTCAGGCACCAAAACATATTTCTGAAAGTCTAGGAGCTGAGGTGGATCCTGATATGTCTTGGTCAAGTTCTTTAGCTACACCACCCACCCTTAGTTCTA
**[TGATCAGGGCATTTCTATAAAAAATAAAC]**TATTTTCTTTCCTCCCAGGGTCGTCAGGCACCAAAACATATTTCTGAAAGTCTAGGAGCTGAGGTGGATCCTGATATGTCTTGGTCAAGTTCTTTAGCTACACCACCCACCCTTAGTTCTA
>rc_chr17:41251910-41251937 <unknown description>
GGCCAACAATTGCTTGACTGTTCTTTAC
**[GGCCAACAATTGCTTGACTGTTCTTTACCA]**TACTGTTTAGCAGGAAACCAGTCTCAGTGTCCAACTCTCTAACCTTGGAACTGTGAGAACTCTGAGGACAAAGCAGCGGATACAACCTCAAAAGACGTCTGTCTACATTGAATTGGGTAA

2.The  non-specific amplification reads are trimmed, and how to discard them?
The 5' end and 3' end are both trimmed, but 5' end primer sequence is not next to the trimmed read sequence.
**41244194CTGAACTACTTCTTCATATTTTGCTTT41244221-41244267**GAGACCTCGGGTTGCAAAACCCCTAATCTAAGCATAGCATTCAATTTTGGCCCTCTGTTTCTACCTAGTTCTGCTTGAATGTTTTCATCACTGGA**41244361-41244362ACCTATTTCATTAATACTGGAGCCCACA41244388**

Very appreciated for your help.
Best Regards,
Amy

**Comment by aakechin** [comment] 2018-04-19 12:42
Amy, could you, please, attach fastq-files with some number (or all, if you can) of your reads (including problem reads) and fasta-files with primer sequences? So I will try to reproduce the problem. In order to be able to attach them here, you will need to change their extension from fastq and fasta to txt.

**Closed as completed** 2020-08-28 07:21 UTC
Labels: help wanted
